# Generated by Django 4.2.20 on 2025-04-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_app', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='item_images/'),
        ),
    ]
